# ==============================================================
# File: banner_html.py
# Version: v0.2.0 | Date: 2026-10-06
# Purpose: The app banner, rendered as HTML and CSS, for surfaces
#          whose width varies.
#
#          banner.py emits a fixed 1440x300 SVG. That is right for
#          a web page or a document and wrong inside an app: a
#          fixed viewBox scales uniformly, so narrowing the column
#          shrinks the type with it.
#
#          EVERY NUMBER COMES FROM tokens/banner_geometry.json,
#          read off the decided drawing. Every colour comes from
#          the registry. This file types neither. If a value is
#          wanted that the geometry has not got, it goes in the
#          geometry file, not here.
#
#          v0.2.0 rebuilt against the decided standard
#          (energy_osx_banner_final_pricing_intelligence.html,
#          12-07-2026; KB_GROUP.md 7.4). The previous version held
#          its own numbers - headline 21 against the SVG's 52, with
#          no shared constant and no test comparing them - which is
#          how two renderings of one banner drifted apart.
# ==============================================================

from __future__ import annotations

import html

from eosx_visual_assets import tokens as T
from eosx_visual_assets.apps import APPS, App
from eosx_visual_assets.geometry import GEOMETRY, colour, part, scale_expr
from eosx_visual_assets.icons import ICON_BOX, glyph

__all__ = ["app_banner_css", "app_banner_html", "headline_lines"]



def headline_lines() -> tuple[str, str, str]:
    """The strapline split into its two rendered lines.

    Returns (first line, joiner, accent). The joiner leads the second line and
    the accent is the coloured phrase.

    Where the break falls is a recorded decision in the geometry file, not a
    reading of the drawing: the 12-07-2026 drawing breaks after the joiner,
    Chris chose 06-10-2026 to break before it.

    Derived from the strapline token, never a second copy of it. If the
    strapline stops containing the joiner the line renders plain, rather than
    being split somewhere invented.
    """
    h = part("platform", "headline")
    joiner = h["joiner"]
    tagline = T.TAGLINE
    marker = " %s " % joiner
    if marker not in tagline:
        return tagline, "", ""
    head, tail = tagline.split(marker, 1)
    if h.get("break_before_joiner", True):
        return head.strip(), joiner, tail.strip()
    return "%s %s" % (head.strip(), joiner), "", tail.strip()


def _text_rule(selector: str, spec: dict, *, extra: str = "") -> str:
    """One text block's CSS, entirely from the geometry."""
    bits = [
        "font-size: %s;" % scale_expr(spec["size"]),
        "font-weight: %d;" % spec["weight"],
        "line-height: %g;" % spec["line_height"],
        "color: %s;" % colour(spec["colour"]),
        "margin: 0 0 %s 0;" % scale_expr(spec["margin_bottom"]),
    ]
    if spec.get("letter_spacing"):
        bits.insert(2, "letter-spacing: %gem;" % spec["letter_spacing"])
    if spec.get("uppercase"):
        bits.append("text-transform: uppercase;")
    if extra:
        bits.append(extra)
    return "%s {\n  %s\n}\n" % (selector, "\n  ".join(bits))


def app_banner_css(*, scope: str = ".eosx-banner") -> str:
    """The stylesheet. One copy, identical for every app.

    Child selectors carry the scope twice on purpose: a host application may
    style text inside its own containers, and one class is easy to outrank.
    Do not flatten them.
    """
    s = scope
    b = part("banner")
    d = part("divider")
    eyebrow = part("platform", "eyebrow")
    headline = part("platform", "headline")
    domains = part("platform", "domains")
    mark = part("app", "mark")
    name = part("app", "name")
    punch = part("app", "punchline")

    stops = ", ".join(
        "%s %g%%" % (c, st * 100) for c, st in zip(T.GRADIENT, T.GRADIENT_STOPS)
    )
    body_font = "'%s', system-ui, sans-serif" % T.FONT_BODY
    head_font = "'%s', system-ui, sans-serif" % T.FONT_HEADING

    css = f"""\
/* Energy OSX app banner - generated by eosx_visual_assets.banner_html.
   Do not edit. Numbers come from tokens/banner_geometry.json, colours from
   brand_tokens.json. Change those, not this. */
{s} {{
  container-type: inline-size;
  background: linear-gradient(90deg, {stops});
  border-radius: {scale_expr(b["radius"])};
  overflow: hidden;
}}
{s} {s}__inner {{
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: {scale_expr(b["gap"])};
  padding: {scale_expr(b["padding_y"])} {scale_expr(b["padding_x"])};
}}
{s} {s}__platform {{
  min-width: 0;
}}
"""
    css += _text_rule("%s %s__eyebrow" % (s, s), eyebrow,
                      extra="font-family: %s;" % body_font)
    css += _text_rule("%s %s__headline" % (s, s), headline,
                      extra="font-family: %s;" % head_font)
    css += ("%s %s__headline em {\n  color: %s;\n  font-style: normal;\n}\n"
            % (s, s, colour(headline["accent_colour"])))
    css += _text_rule("%s %s__domains" % (s, s), domains,
                      extra="font-family: %s;" % body_font)
    css += f"""\
{s} {s}__app {{
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  text-align: right;
  flex: 0 0 auto;
  border-left: {d["width"]}px solid {colour("divider")};
  padding-left: {scale_expr(d["padding_left"])};
}}
"""
    css += _text_rule(
        "%s %s__appname" % (s, s), name,
        extra=("font-family: %s;\n  display: flex;\n  align-items: center;\n"
               "  justify-content: flex-end;\n  gap: %s;"
               % (head_font, scale_expr(mark["gap"]))))
    css += f"""\
{s} {s}__mark {{
  width: {scale_expr(mark["size"])};
  height: {scale_expr(mark["size"])};
  flex: 0 0 auto;
  display: block;
}}
"""
    css += _text_rule("%s %s__punchline" % (s, s), punch,
                      extra="font-family: %s;" % body_font)
    css += f"""\
/* Below this the two zones stop fitting side by side. The app zone moves
   under the platform zone rather than the type shrinking past legibility. */
@container (max-width: {GEOMETRY["stack_below"]}px) {{
  {s} {s}__inner {{
    flex-direction: column; align-items: flex-start;
    gap: {scale_expr(GEOMETRY["stack_gap"])};
  }}
  {s} {s}__app {{
    align-items: flex-start; text-align: left; width: 100%;
    border-left: 0; border-top: {d["width"]}px solid {colour("divider")};
    padding-left: 0; padding-top: {scale_expr(GEOMETRY["stack_padding_top"])};
  }}
}}
"""
    return css


def app_banner_html(app: App | str, *, include_css: bool = False,
                    scope: str = ".eosx-banner") -> str:
    """The banner markup for one app.

    The left platform zone is byte-identical for every app. The right zone is
    the only part that varies, and only by what the registry says.
    """
    if isinstance(app, str):
        try:
            app = APPS[app]
        except KeyError:
            raise KeyError(
                "%r is not in the registry. Add it to brand_tokens.json "
                "rather than passing a name through." % app
            ) from None

    head, joiner, accent = headline_lines()
    headline = html.escape(head)
    if accent:
        tail = ("%s <em>%s</em>" % (html.escape(joiner), html.escape(accent))
                if joiner else "<em>%s</em>" % html.escape(accent))
        headline += "<br>%s" % tail

    cls = scope.lstrip(".")
    mark = glyph(app.icon, stroke=T.ACCENT_TEAL, fill=T.ACCENT_TEAL, sw=2.6)
    css = "<style>\n%s</style>\n" % app_banner_css(scope=scope) if include_css else ""

    return f"""{css}<div class="{cls}">
  <div class="{cls}__inner">
    <div class="{cls}__platform">
      <p class="{cls}__eyebrow">{html.escape(T.WORDMARK)}</p>
      <p class="{cls}__headline">{headline}</p>
      <p class="{cls}__domains">{html.escape(" · ".join(T.DOMAINS))}</p>
    </div>
    <div class="{cls}__app">
      <p class="{cls}__appname">
        <svg class="{cls}__mark" viewBox="0 0 {ICON_BOX} {ICON_BOX}" aria-hidden="true">{mark}</svg>
        <span>{html.escape(app.name)}</span>
      </p>
      <p class="{cls}__punchline">{html.escape(app.punchline)}</p>
    </div>
  </div>
</div>
"""
