# ==============================================================
# File: banner_html.py
# Version: v0.1.0 | Date: 2026-10-05
# Purpose: The app banner, rendered as HTML and CSS instead of
#          SVG, for surfaces whose width varies.
#
#          banner.py emits a fixed 1440x300 SVG. That is right for
#          a web page or a document and wrong inside an app: a
#          fixed viewBox scales uniformly, so narrowing the column
#          shrinks the type with it. This module emits the same
#          banner as markup that reflows, with the type scale held
#          in proportion by one multiplier.
#
#          Every value comes from the registry. Nothing here is
#          typed, and nothing varies per app except the right-hand
#          zone - the glyph, the app name and the punch line.
#          KB_GROUP.md section 7.4 is the rule this implements.
# ==============================================================

from __future__ import annotations

import html

from eosx_visual_assets import tokens as T
from eosx_visual_assets.apps import APPS, App
from eosx_visual_assets.icons import ICON_BOX, glyph

# Reference geometry, from the shared banner spec (v1.0.0, 12-07-2026).
# These are the sizes at full width; everything scales from them together,
# which is what makes two apps at different widths still look like one system.
PAD_Y, PAD_X = 26, 28
RADIUS = 10
GAP = 32
DIVIDER_PAD = 28
SIZE_EYEBROW = 11
SIZE_HEADLINE = 21
SIZE_DOMAINS = 11
SIZE_APP_NAME = 17
SIZE_PUNCHLINE = 10
MARK = 22          # app glyph box, left of the app name
MARK_GAP = 9

#: Width the reference sizes are quoted at.
REFERENCE_WIDTH = 1440

__all__ = ["app_banner_css", "app_banner_html", "REFERENCE_WIDTH"]


def _gradient_css() -> str:
    """The platform gradient, from on_dark - never retyped."""
    stops = ", ".join(
        "%s %s%%" % (colour, round(stop * 100, 2))
        for colour, stop in zip(T.GRADIENT, T.GRADIENT_STOPS)
    )
    return "linear-gradient(90deg, %s)" % stops


def _headline_parts() -> tuple[str, str, str]:
    """Split the strapline into its two rendered lines.

    The spec sets "energy intelligence" in the accent teal on line two. That
    phrase is derived from the token, not held as a second copy of it - if the
    strapline changes, this follows, and if it stops matching the shape the
    whole line renders plain rather than inventing a split.
    """
    tagline = T.TAGLINE
    marker = " for "
    if marker in tagline:
        head, tail = tagline.split(marker, 1)
        return head.strip(), "for", tail.strip()
    return tagline, "", ""


def app_banner_css(*, scope: str = ".eosx-banner") -> str:
    """The stylesheet. One copy, identical for every app.

    `scope` only renames the class, for an app whose CSS would otherwise
    collide. It changes no value.
    """
    grad = _gradient_css()
    s = scope
    return f"""\
/* Energy OSX app banner - generated by eosx_visual_assets.banner_html.
   Do not edit. Every value comes from brand_tokens.json. */
/* Every child selector carries the scope twice. That is deliberate: a host
   application may colour text inside its own container - Streamlit does, with
   `[data-testid="stMarkdownContainer"] p` - and a single-class rule loses to
   it, which turned the whole platform zone invisible on a dark bar. Two
   classes outrank one class plus one element. Do not flatten these. */
{s} {{
  container-type: inline-size;
  background: {grad};
  border-radius: {RADIUS}px;
  overflow: hidden;
}}
{s} {s}__inner {{
  /* One multiplier drives every size below, so the proportions hold at any
     width. 1 at the reference width, never below 0.72 or the type stops
     being legible. cqi needs the container above; the plain value is the
     fallback where container queries are unavailable. */
  --eosx-b: 1;
  --eosx-b: clamp(0.72, calc(100cqi / {REFERENCE_WIDTH}px), 1);
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: calc({GAP}px * var(--eosx-b));
  padding: calc({PAD_Y}px * var(--eosx-b)) calc({PAD_X}px * var(--eosx-b));
}}
{s} {s}__eyebrow {{
  font-family: '{T.FONT_BODY}', system-ui, sans-serif;
  font-size: calc({SIZE_EYEBROW}px * var(--eosx-b));
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: {T.MUTED_TEAL};
  margin: 0 0 calc(10px * var(--eosx-b)) 0;
}}
{s} {s}__headline {{
  font-family: '{T.FONT_HEADING}', system-ui, sans-serif;
  font-size: calc({SIZE_HEADLINE}px * var(--eosx-b));
  font-weight: 500;
  line-height: 1.25;
  color: {T.WHITE};
  margin: 0;
}}
{s} {s}__headline em {{ color: {T.ACCENT_TEAL}; font-style: normal; }}
{s} {s}__domains {{
  font-family: '{T.FONT_BODY}', system-ui, sans-serif;
  font-size: calc({SIZE_DOMAINS}px * var(--eosx-b));
  letter-spacing: 0.03em;
  color: {T.SUBLABEL};
  margin: calc(10px * var(--eosx-b)) 0 0 0;
}}
{s} {s}__app {{
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  text-align: right;
  border-left: 1px solid {T.DIVIDER};
  padding-left: calc({DIVIDER_PAD}px * var(--eosx-b));
  flex: 0 0 auto;
}}
{s} {s}__appname {{
  display: flex;
  align-items: center;
  gap: calc({MARK_GAP}px * var(--eosx-b));
  font-family: '{T.FONT_HEADING}', system-ui, sans-serif;
  font-size: calc({SIZE_APP_NAME}px * var(--eosx-b));
  font-weight: 500;
  color: {T.WHITE};
  margin: 0;
}}
{s} {s}__mark {{
  width: calc({MARK}px * var(--eosx-b));
  height: calc({MARK}px * var(--eosx-b));
  flex: 0 0 auto;
  display: block;
}}
{s} {s}__punchline {{
  font-family: '{T.FONT_BODY}', system-ui, sans-serif;
  font-size: calc({SIZE_PUNCHLINE}px * var(--eosx-b));
  letter-spacing: 0.16em;
  font-weight: 600;
  text-transform: uppercase;
  color: {T.MUTED_TEAL};
  margin: calc(8px * var(--eosx-b)) 0 0 0;
}}
/* Below this the two zones stop fitting side by side. The app zone moves
   under the platform zone rather than the type shrinking past legibility. */
@container (max-width: 560px) {{
  {s} {s}__inner {{
    flex-direction: column; align-items: flex-start;
    gap: calc(18px * var(--eosx-b));
  }}
  {s} {s}__app {{
    align-items: flex-start; text-align: left; width: 100%;
    border-left: 0; border-top: 1px solid {T.DIVIDER};
    padding-left: 0; padding-top: calc(16px * var(--eosx-b));
  }}
}}
"""


def app_banner_html(app: App | str, *, include_css: bool = False,
                    scope: str = ".eosx-banner") -> str:
    """The banner markup for one app.

    The left platform zone is byte-identical for every app. The right zone is
    the only part that varies, and it varies only by what the registry says.
    """
    if isinstance(app, str):
        try:
            app = APPS[app]
        except KeyError:
            raise KeyError(
                "%r is not in the registry. Add it to brand_tokens.json rather "
                "than passing a name through." % app
            ) from None

    head, joiner, accent = _headline_parts()
    headline = html.escape(head)
    if joiner:
        headline += "<br>%s <em>%s</em>" % (html.escape(joiner), html.escape(accent))

    cls = scope.lstrip(".")
    mark = glyph(app.icon, stroke=T.ACCENT_TEAL, fill=T.ACCENT_TEAL, sw=2.6)
    css = "<style>\n%s</style>\n" % app_banner_css(scope=scope) if include_css else ""

    return f"""{css}<div class="{cls}">
  <div class="{cls}__inner">
    <div class="{cls}__platform">
      <p class="{cls}__eyebrow">{html.escape(T.WORDMARK)}</p>
      <p class="{cls}__headline">{headline}</p>
      <p class="{cls}__domains">{html.escape(" · ".join(T.DOMAINS))}</p>
    </div>
    <div class="{cls}__app">
      <p class="{cls}__appname">
        <svg class="{cls}__mark" viewBox="0 0 {ICON_BOX} {ICON_BOX}" aria-hidden="true">{mark}</svg>
        <span>{html.escape(app.name)}</span>
      </p>
      <p class="{cls}__punchline">{html.escape(app.punchline)}</p>
    </div>
  </div>
</div>
"""
