# ==============================================================
# File: web.py
# Version: v0.1.0 | Date: 2026-10-05
# Purpose: Emit the brand for TypeScript apps.
#
#          banner_html.py returns an HTML string, which suits
#          Streamlit and is wrong in React: a string forced through
#          dangerouslySetInnerHTML has no props, no types, and puts
#          a Python build step inside a TypeScript pipeline.
#
#          This writes three generated files the React apps import
#          directly - the registry as typed TypeScript, the
#          stylesheet, and the component. Nothing here is a second
#          copy: every value is read from brand_tokens.json at
#          generation time, and tests/test_web_emit.py renders the
#          component with node and asserts it matches the Python
#          output character for character.
#
#          Generated. Do not edit the output; change the registry
#          or this emitter and run `eosx-assets-build --web`.
# ==============================================================

from __future__ import annotations

import json
from pathlib import Path

from eosx_visual_assets import tokens as T
from eosx_visual_assets.apps import APPS
from eosx_visual_assets.banner_html import (
    REFERENCE_WIDTH,
    _headline_parts,
    app_banner_css,
)
from eosx_visual_assets.icons import ICON_BOX, glyph

__all__ = ["tokens_ts", "banner_tsx", "emit_web"]

_BANNER = "eosx-banner"

_HEADER = (
    "// Generated by eosx_visual_assets.web - do not edit.\n"
    "// Source: brand_tokens.json. Change the registry, not this file.\n"
)


def tokens_ts() -> str:
    """The registry as a typed TypeScript module."""
    head, joiner, accent = _headline_parts()
    slugs = sorted(APPS)
    apps = {
        s: {"name": APPS[s].name, "punchline": APPS[s].punchline, "icon": APPS[s].icon}
        for s in slugs
    }
    glyphs = {
        APPS[s].icon: glyph(APPS[s].icon, stroke=T.ACCENT_TEAL, fill=T.ACCENT_TEAL, sw=2.6)
        for s in slugs
    }
    colours = {
        "deepNavy": T.DEEP_NAVY, "navy": T.NAVY, "teal": T.TEAL, "aqua": T.AQUA,
        "mist": T.MIST, "ice": T.ICE, "white": T.WHITE, "slate": T.SLATE,
        "border": T.BORDER, "accentTeal": T.ACCENT_TEAL, "mutedTeal": T.MUTED_TEAL,
        "sublabel": T.SUBLABEL, "divider": T.DIVIDER,
    }
    j = lambda o: json.dumps(o, indent=2, ensure_ascii=False)  # noqa: E731
    union = " | ".join('"%s"' % s for s in slugs)
    return f"""{_HEADER}
export const colours = {j(colours)} as const;

export const gradient = {j(list(T.GRADIENT))} as const;
export const gradientStops = {j(list(T.GRADIENT_STOPS))} as const;

export const fonts = {j({"heading": T.FONT_HEADING, "body": T.FONT_BODY,
                        "mono": T.FONT_MONO})} as const;

/** The platform zone. Identical on every app - never edited per app. */
export const platform = {j({
    "wordmark": T.WORDMARK,
    "strapline": {"head": head, "joiner": joiner, "accent": accent},
    "domains": list(T.DOMAINS),
})} as const;

export const bannerGeometry = {j({"referenceWidth": REFERENCE_WIDTH,
                                  "iconBox": ICON_BOX})} as const;

export type AppSlug = {union};

export interface AppBrand {{
  name: string;
  punchline: string;
  icon: string;
}}

export const apps: Record<AppSlug, AppBrand> = {j(apps)};

/** Inner SVG markup for each glyph, drawn in a {ICON_BOX}x{ICON_BOX} box. */
export const glyphs: Record<string, string> = {j(glyphs)};
"""


def banner_tsx() -> str:
    """The React component. Same DOM as app_banner_html, asserted by test."""
    b = _BANNER
    return f"""{_HEADER}
import {{ apps, glyphs, platform, bannerGeometry, type AppSlug }} from "./tokens";

export interface BannerProps {{
  /** Which app's banner to render. Must be in the registry. */
  app: AppSlug;
}}

/**
 * The Energy OSX app banner.
 *
 * The left platform zone is identical on every app; only the right zone
 * varies, and only by what the registry says. Import `banner.css` once,
 * anywhere in the app.
 *
 * The glyph is injected as markup because it is generated SVG from the
 * registry, not user content.
 */
export function Banner({{ app }}: BannerProps) {{
  const brand = apps[app];
  if (!brand) {{
    throw new Error(
      `${{app}} is not in the registry. Add it to brand_tokens.json ` +
        `rather than passing a name through.`
    );
  }}
  const {{ head, joiner, accent }} = platform.strapline;

  return (
    <div className="{b}">
      <div className="{b}__inner">
        <div className="{b}__platform">
          <p className="{b}__eyebrow">{{platform.wordmark}}</p>
          <p className="{b}__headline">
            {{head}}
            <br />
            {{joiner}} <em>{{accent}}</em>
          </p>
          <p className="{b}__domains">{{platform.domains.join(" \\u00b7 ")}}</p>
        </div>
        <div className="{b}__app">
          <p className="{b}__appname">
            <svg
              className="{b}__mark"
              viewBox={{`0 0 ${{bannerGeometry.iconBox}} ${{bannerGeometry.iconBox}}`}}
              aria-hidden="true"
              dangerouslySetInnerHTML={{{{ __html: glyphs[brand.icon] }}}}
            />
            <span>{{brand.name}}</span>
          </p>
          <p className="{b}__punchline">{{brand.punchline}}</p>
        </div>
      </div>
    </div>
  );
}}

export default Banner;
"""


def emit_web(out_dir: Path) -> list[Path]:
    """Write the three generated files. Returns what it wrote."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, body in (
        ("tokens.ts", tokens_ts()),
        ("Banner.tsx", banner_tsx()),
        ("banner.css", app_banner_css()),
    ):
        p = out_dir / name
        p.write_text(body, encoding="utf-8", newline="\n")
        written.append(p)
    return written
